"""sync users table

Revision ID: d5e9b2f21a08
Revises: 
Create Date: 2026-07-23 14:39:48.837421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5e9b2f21a08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_logs')
    op.drop_table('notifications')
    op.drop_table('waste_reasons')
    op.drop_table('categories')
    op.drop_table('ocr_scans')
    op.drop_table('ingredients')
    op.drop_table('units')
    op.drop_table('recipes')
    op.drop_table('food_items')
    op.drop_table('recipe_ingredients')
    op.drop_table('devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fcm_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('platform', mysql.ENUM('android', 'ios'), nullable=True),
    sa.Column('last_active_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('devices_ibfk_1')),
    sa.PrimaryKeyConstraint('device_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_optional', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name=op.f('recipe_ingredients_ibfk_2')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], name=op.f('recipe_ingredients_ibfk_1')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], name=op.f('recipe_ingredients_ibfk_3')),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('food_items',
    sa.Column('item_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('quantity', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('fresh', 'expiring', 'expired', 'consumed'), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('added_via', mysql.ENUM('manual', 'ocr'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('food_items_ibfk_3')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name=op.f('food_items_ibfk_2')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], name=op.f('food_items_ibfk_4')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('food_items_ibfk_1')),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recipes',
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('instructions', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('cook_time_minutes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('servings', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('units',
    sa.Column('unit_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('abbreviation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('unit_type', mysql.ENUM('weight', 'volume', 'count'), nullable=True),
    sa.Column('conversion_factor', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ingredients',
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name_th', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('name_en', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('aliases', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('ingredients_ibfk_1')),
    sa.PrimaryKeyConstraint('ingredient_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ocr_scans',
    sa.Column('scan_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('raw_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('detected_date', sa.DATE(), nullable=True),
    sa.Column('confidence', mysql.FLOAT(), nullable=True),
    sa.Column('was_corrected', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('scanned_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['food_items.item_id'], name=op.f('ocr_scans_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('ocr_scans_ibfk_1')),
    sa.PrimaryKeyConstraint('scan_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categories',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_th', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('name_en', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('waste_reasons',
    sa.Column('reason_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label_th', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('label_en', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('reason_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('notif_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.ENUM('expiry', 'waste'), nullable=True),
    sa.Column('message', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('scheduled_at', mysql.DATETIME(), nullable=True),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['food_items.item_id'], name=op.f('notifications_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('notifications_ibfk_1')),
    sa.PrimaryKeyConstraint('notif_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('waste_logs',
    sa.Column('waste_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_wasted', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('wasted_at', sa.DATE(), nullable=True),
    sa.Column('note', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['food_items.item_id'], name=op.f('waste_logs_ibfk_2')),
    sa.ForeignKeyConstraint(['reason_id'], ['waste_reasons.reason_id'], name=op.f('waste_logs_ibfk_4')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], name=op.f('waste_logs_ibfk_3')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('waste_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('waste_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
